
  CREATE TABLE "CITY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(2), 
	"WIDTH" NUMBER, 
	"LENGTH" NUMBER, 
	"ACTIVE" VARCHAR2(1), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CITY_UK" UNIQUE ("NAME", "COUNTRY")
  USING INDEX  ENABLE
   ) ;