
  CREATE TABLE "WEATHER_RAW" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DOWNLOAD_DATE" TIMESTAMP (6) DEFAULT systimestamp, 
	"CITY_ID" NUMBER, 
	"JSON_RESPONSE" CLOB, 
	"STATUS_HTTP" NUMBER, 
	 CONSTRAINT "JSON_CHECK" CHECK (json_response is json) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "WEATHER_RAW" ADD CONSTRAINT "WEATHER_RAW_CON" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CITY" ("ID") ON DELETE CASCADE ENABLE;