
  CREATE TABLE "WEATHER_PROCESSED" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CITY_ID" NUMBER, 
	"MEASUREMENT_DATE" TIMESTAMP (6), 
	"TEMP" NUMBER, 
	"HUMIDITY" NUMBER, 
	"PRESSURE" NUMBER, 
	"WIND_SPEED" NUMBER, 
	"WIND_DIRECTION" VARCHAR2(10), 
	"RAINFALL" NUMBER, 
	"CLOUDY" NUMBER, 
	"WEATHER_DESCRIBE" VARCHAR2(200), 
	"ICON" VARCHAR2(10), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "WEATHER_PROCESSED" ADD CONSTRAINT "WEATHER_PROCESSED_CON" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CITY" ("ID") ENABLE;